---
  - hosts: all
    become: yes
    vars:
      base_dir: '/var/www/lisb/'
    tasks:
    
    # Install dependencies

    - name: Install necessary dependencies 
      apt:
        name: [
          'git', 
          'nginx', 
          'python3-pip', 
          'python3-dev', 
          'build-essential', 
          'libssl-dev', 
          'libffi-dev', 
          'python3-setuptools', 
          'python3', 
          'python3-venv', 
          'virtualenv', 
          'python3-virtualenv',
          'libblas3',
          'liblapack3',
          'liblapack-dev',
          'libblas-dev',
          'gfortran'
        ]
        state: latest
        update_cache: yes

    # Setting up working directory

    - name: Clone GitHub repository in which the spam filter SMTP server is located
      ansible.builtin.git:
        repo: 'https://github.com/sing-group/LiSB.git'
        dest: "{{ base_dir }}"

    - name: Add execution permissions to the SMTP server launcher script
      file:
        path: "{{ base_dir }}launcher.py"
        mode: u+x

    - name: Add execution permissions to the SMTP server scripts directory
      file:
        path: "{{ base_dir }}core/scripts/"
        state: directory
        recurse: yes
        mode: u+x

    # Set up virtual environment for SMTP server

    - name: Manually create the project's virtualenv
      command:
        cmd: python3.7 -m venv {{ base_dir }}venv
        creates: "{{ base_dir }}venv"

    - name: Install specified python requirements in indicated (virtualenv)
      command:
        cmd: "{{ base_dir }}venv/bin/pip install -r {{ base_dir }}requirements.txt --upgrade"

    # Set up flask web server with uWSGI and NGINX  
  
    - name: Change owner to admin and group to www-data
      file:
        dest: "{{ base_dir }}"
        owner: admin
        group: www-data
        recurse: yes

    - name: Delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create systemd unit file that reloads the server upon reboot
      template:
        src: templates/webserver/lisbweb.service.j2
        dest: /etc/systemd/system/lisbweb.service
    
    - name: Start uWSGI service
      systemd: 
        name: lisbweb
        state: started
    
    - name: Enable uWSGI service
      command: 
        cmd: systemctl enable lisbweb
    
    - name: Configure NGINX for proxy requests
      template:
        src: templates/webserver/lisbweb.j2
        dest: /etc/nginx/sites-available/lisbweb

    - name: Create symlink to enabled sites
      file:
        src: /etc/nginx/sites-available/lisbweb
        dest: /etc/nginx/sites-enabled/lisbweb
        state: link

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    # Set up LiSBServer as systemd daemon

    - name: Create systemd unit file that reloads the SMTP server upon reboot
      template:
        src: templates/lisbserver.service.j2
        dest: /etc/systemd/system/lisbserver.service
    
    - name: Enable SMTP service
      systemd: 
        name: lisbserver
        state: started
    
    - name: Enable SMTP service
      command: 
        cmd: systemctl enable lisbserver
     
